from typing import Any

ABS3Solver: Any
ABS3SolverSol: Any
AmplifySolver: Any
AmplifySolverSol: Any
CallbackEvent: Any
CbcSolver: Any
CbcSolverSol: Any
CplexSolver: Any
CplexSolverSol: Any
DWaveHybridSolver: Any
DWaveHybridSolverSol: Any
DWaveNativeSolver: Any
DWaveNealSolver: Any
DWaveNealSolverSol: Any
DWaveSolver: Any
DWaveSolverSol: Any
DWaveSteepestDescentSolver: Any
DWaveSteepestDescentSolverSol: Any
DWaveTabuSolver: Any
DWaveTabuSolverSol: Any
DimodExactSolver: Any
DimodExactSolverSol: Any
EasySolver: Any
EasySolverSol: Any
ExhaustiveSolver: Any
ExhaustiveSolverSol: Any
Expr: Any
GlpkSolver: Any
GlpkSolverSol: Any
GurobiSolver: Any
GurobiSolverSol: Any
HighsSolver: Any
HighsSolverSol: Any
HobotanMikasSolver: Any
HobotanMikasSolverSol: Any
IntVar: Any
Model: Any
OpenJijSolver: Any
OpenJijSolverSol: Any
OrToolsCpSatSolver: Any
OrToolsCpSatSolverSol: Any
QiskitOptimizationSolver: Any
QiskitOptimizationSolverSol: Any
QubovertSolver: Any
QubovertSolverSol: Any
ScipSolver: Any
ScipSolverSol: Any
SimulatedBifurcationSolver: Any
SimulatedBifurcationSolverSol: Any
Sol: Any
SolverSol: Any
Term: Any
VINDEX_INT_BIT: Any
VINDEX_LIMIT: Any
VINDEX_NEG_BIT: Any
Var: Any
VarIntArray: Any
array: Any
binarize: Any
binary_to_spin: Any
concat: Any
cons: Any
constrain: Any
copy: Any
einsum: Any
expand_cons: Any
expr: Any
gcd: Any
inf: Any
license_key: Any
onehot_to_int: Any
ones: Any
reduce: Any
replace: Any
same: Any
simplify_as_binary: Any
simplify_as_spin: Any
spin_to_binary: Any
sqr: Any
sum: Any
var: Any
vector_sum: Any
zeros: Any